steps:
  - topic: topic1
    message: Topic1 Msg
    number_of_times: 1
    sleep_between_messages: 0
    sleep_after: 0
  # - topic: topic2
  #   message: Topic2 Msg
  #   number_of_times: 5
  #   sleep_between_messages: 0
  #   sleep_after: 5
  # - topic: topic2
  #   message: Topic2 Msg Yes!!
  #   number_of_times: 20
  #   sleep_between_messages: 0
  #   sleep_after: 1
